name: Build and Launch Docker Image Locally

on:
  push:
    branches:
      - main  # Adjust to the branch you want this action to trigger on
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    
    - name: Build Docker image
      run: |
        docker build -t my-app:${{ github.sha }} -f Dockerfile
        docker tag my-app:${{ github.sha }} my-app:latest

    # Step 3: Deploy Docker container locally
    - name: Deploy Docker container
      run: |
        docker run -d -p 80:80 --name my-app my-app:latest
