name: Build and Launch Docker Image Locally

on:
  push:
    branches:
      - main  # Adjust to the branch you want this action to trigger on
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    steps:
        # Step 1: Set up cache directory for Docker
        - name: Set up Docker layer cache
          uses: actions/cache@v3
          with:
            path: /tmp/.buildx-cache
            key: ${{ runner.os }}-docker-${{ github.sha }}
            restore-keys: |
              ${{ runner.os }}-docker-
    
    - name: Build Docker image
      run: |
        docker build -t my-app:${{ github.sha }} -f Dockerfile .
        docker tag my-app:${{ github.sha }} my-app:latest

    # Step 3: Deploy Docker container locally
    - name: Deploy Docker container
      run: |
        docker run -d -p 8080:8080 -p 8501:8501 -p 8502:8502 --name my-app my-app:latest 

  

